
//
// _DPathCG_h_
//
// Copyright (C) 2017-2020 Tactical Computing Laboratories, LLC
// All Rights Reserved
// contact@tactcomplabs.com
//
// See LICENSE in the top level directory for licensing details
//

/**
 * \class DPathCG
 *
 * \ingroup CoreGenCodegen
 *
 * \brief DPathCG generates the datapath implementation capable of executing the instructions 
 * generated by the CoreGen uCode compiler
 *
 */


#ifndef _DPATHCG_H_
#define _DPATHCG_H_

#include "CoreGen/CoreGenCodegen/CoreGenNodeCodegen.h"

class DPathCG : public CoreGenNodeCodegen {
private:
    
    bool    GenSharedBus(std::ofstream &O);

    bool    GenInstDispatch(std::ofstream &O ) { return false;};

    bool    GenALU(std::ofstream &O ){return false; };

public:

    DPathCG(CoreGenNode *N,
            CoreGenProj *P,
            std::string Package,
            std::string Path,
            bool Common,
            CoreGenErrno *E );

    bool    Execute( );

};

#endif
